# Generated by Django 3.0.2 on 2020-02-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_auto_20200209_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection',
            new_name='Connections',
        ),
    ]
